### ISSUE TITLE
Bug: Unable to load any models 

### ISSUE THREAD

**Issue by VinneyUK** [CarlGao4/Demucs-Gui#45] opened 2024-01-21 19:51 UTC
### happen

1.  When selecting modelling, they appear not to download
2. 

### What is the platform you are using?

macOS

### log

```true
024-01-21 19:48:49,138 (shared.py) (Line 167) [INFO] : [2] Thread loadModel (GuiMain.py) ends
2024-01-21 19:49:22,733 (shared.py) (Line 161) [INFO] : [3] Thread loadModel (GuiMain.py) starts
2024-01-21 19:49:22,734 (GuiMain.py) (Line 368) [INFO] : Loading model mdx from repo "remote"
Downloading: "https://dl.fbaipublicfiles.com/demucs/mdx_final/0d19c1c6-0f06f20e.th" to /Users/Vinney/.cache/torch/hub/checkpoints/0d19c1c6-0f06f20e.th
2024-01-21 19:49:22,772 (GuiMain.py) (Line 241) [ERROR] : Failed to load model mdx from remote repo:
Traceback (most recent call last):
  File "urllib/request.py", line 1348, in do_open
  File "http/client.py", line 1286, in request
  File "http/client.py", line 1332, in _send_request
  File "http/client.py", line 1281, in endheaders
  File "http/client.py", line 1041, in _send_output
  File "http/client.py", line 979, in send
  File "http/client.py", line 1458, in connect
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1108, in _create
  File "ssl.py", line 1379, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GuiMain.py", line 239, in loadModel
  File "separator.py", line 165, in __init__
  File "demucs/api.py", line 119, in __init__
  File "demucs/api.py", line 204, in _load_model
  File "demucs/pretrained.py", line 78, in get_model
  File "demucs/repo.py", line 160, in get_model
  File "demucs/repo.py", line 139, in get_model
  File "demucs/repo.py", line 139, in <listcomp>
  File "demucs/repo.py", line 68, in get_model
  File "torch/hub.py", line 746, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "torch/hub.py", line 611, in download_url_to_file
    u = urlopen(req)
        ^^^^^^^^^^^^
  File "urllib/request.py", line 216, in urlopen
  File "urllib/request.py", line 519, in open
  File "urllib/request.py", line 536, in _open
  File "urllib/request.py", line 496, in _call_chain
  File "urllib/request.py", line 1391, in https_open
  File "urllib/request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>

2024-01-21 19:49:22,773 (shared.py) (Line 167) [INFO] : [3] Thread loadModel (GuiMain.py) ends
```

**Comment by CarlGao4** [comment] 2024-01-27 10:45
Duplicate of #44

**Closed** 2024-01-27 11:00 UTC
Labels: bug
