### ISSUE TITLE
4.0 version Gui

### ISSUE THREAD

**Issue by KimHBin** [CarlGao4/Demucs-Gui#17] opened 2023-02-24 06:19 UTC
When can we expect to see the GUI of version 4.0?

**Comment by CarlGao4** [comment] 2023-02-24 09:15
As I've said in README: 
**This project is temporarily suspended, development will be resumed when the developers are available**

**Comment by CarlGao4** [comment] 2023-02-24 09:16
If you'd like to have an exact date, I can only say that it will not earlier than June

**Comment by KimHBin** [comment] 2023-02-24 09:21
> 

Thanks for the reply
Is the gui program you provide different from "Ultimate Vocal Remover"?

**Comment by CarlGao4** [comment] 2023-02-24 09:23
> Is the gui program you provide different from "Ultimate Vocal Remover"?

That's true.

**Comment by CarlGao4** [comment] 2023-09-08 00:16
Duplicate of #18

**Closed by CarlGao4** 2023-09-08 00:16 UTC
Labels: question
